### ISSUE TITLE
MIDI Polyphonic AfterTouch or ChannelPressure results in "undefined"

### ISSUE THREAD

**Issue by espoelstra** [ryoyakawai/midimessageviewer#2]
I just found your excellent resource for testing WebMIDI and BLE-MIDI via WebBluetooth devices [here](https://ryoyakawai.com/apps/midimsgv/index.html) and while playing around with my ROLI LUMI I noticed that if I held down a key after pressing it then it was sending a message your site was slightly confused about. This keyboard supports Polyphonic AfterTouch so I have a feeling that is the message that is confusing it.

![Screenshot 2020-05-18 at 9 30 17 PM](https://user-images.githubusercontent.com/7798975/82278123-0f840d80-994f-11ea-8dc6-9b11668f9cb1.png)

I think that you could possibly parse the value of the Polyphonic AfterTouch and/or the Channel Pressure similar to how you parse the Velocity at least according to the MIDI spec.

https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

Or more concisely put in this Sound.SE answer.

https://sound.stackexchange.com/a/24089

**Comment by ryoyakawai** [comment]
Thank you for letting me know this. 
I think you are right. I will investigate the situation, and will fix ASAP this after the investigation.

**Comment by ryoyakawai** [comment]
@espoelstra 
The app is now updated.
Unfortunately, I do not own the gear that has ability to send AfterTouch or ChannelPressure message, so the app is not tested enough. So if the app behave such as displaying as undefined as same as before, please let me know :-)

https://github.com/ryoyakawai/midimessageviewer/commit/5e8e6aae2bd12f2b990e3ea49a740d09c9b174a7

**Comment by espoelstra** [comment]
Looks like that fixed it for the ROLI LUMI that I was testing with. It can be tricky to activate AfterTouch vs a sustain, but I'm not an accomplished enough musician to know the difference yet.

![Screenshot 2020-05-24 at 5 33 41 PM](https://user-images.githubusercontent.com/7798975/82766438-d2070080-9de4-11ea-8ac9-7e39ffbbb5ca.png)

**Comment by ryoyakawai** [comment]
@espoelstra 
Thank you very much for testing the app!!
I am happy to hear that :-)

As per my research, there are two different messages are defined in MIDI spec to express "After Touch". One is Polyphonic Pressure and the other is Channel pressure. The message of 'Polyphonic Pressure' defined as the message effective for each individual key whereas 'Channel Pressure' defined as the message effective for each channel. So 'Polyphonic Pressure' has ability playing precise expression than 'Channel Pressure'.
And as you are mentioning, I also think that is tricky to send desired message from these two since I think it is really depending on implementation of firmware.

By the way, I am happy to see the people playing with my app on Chrome OS. I am one of fan of Chrome OS as well.
